name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: singhealthllmdemo
        # Container registry password
        password: g9bU5FZuUm1GKPl0l8GnAJkxH69o6W3jFtr2SCIH40+ACRDwUkiz
        # Container registry server url
        login-server: singhealthllmdemo.azurecr.io
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:         
        docker build . --file WebApp.Dockerfile --tag singhealthllmdemo.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag singhealthllmdemo.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER singhealthllmdemo.azurecr.io/sample-app-aoai-chatgpt:latest;
        docker push singhealthllmdemo.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push singhealthllmdemo.azurecr.io/sample-app-aoai-chatgpt:latest;
      
